[package]
name = "template_example"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_mobius_template = { path = "../.." }
eframe = "0.31.1"
egui = "0.31.1"
egui_dock = "0.16.0"
egui_mobius_widgets = "0.3.0-alpha.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
