[package]
name = "template_example"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_mobius_template = { path = "../.." }
eframe = "0.32"
egui = "0.32"
egui_dock = "0.17.0"
egui_mobius_widgets = "0.3.0-alpha.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
